#!/usr/bin/env python3
"""
Converts circuit outlines from github.com/bacinger/f1-circuits (MIT, (c) Tomislav Bacinger)
into src/sim/circuitShapes.ts.

Usage: python3 scripts/import-circuits.py path/to/f1-circuits.geojson
Coordinates are projected to local metres (x east, y south) and centred.
The first point is the start/finish line; order follows the racing direction.
"""
import json, math, sys

# game id -> dataset id
IDS = {
    'melbourne': 'au-1953', 'shanghai': 'cn-2004', 'suzuka': 'jp-1962', 'bahrain': 'bh-2002',
    'jeddah': 'sa-2021', 'miami': 'us-2022', 'montreal': 'ca-1978', 'monaco': 'mc-1929',
    'barcelona': 'es-1991', 'spielberg': 'at-1969', 'silverstone': 'gb-1948', 'spa': 'be-1925',
    'hungaroring': 'hu-1986', 'zandvoort': 'nl-1948', 'monza': 'it-1922', 'madring': 'es-2026',
    'baku': 'az-2016', 'singapore': 'sg-2008', 'austin': 'us-2012', 'mexico': 'mx-1962',
    'interlagos': 'br-1940', 'lasvegas': 'us-2023', 'lusail': 'qa-2004', 'yasmarina': 'ae-2009',
}

data = json.load(open(sys.argv[1]))
feats = {f['properties']['id']: f for f in data['features']}
out = ['// AUTO-GENERATED by scripts/import-circuits.py — do not edit by hand.',
       '// Circuit outlines: github.com/bacinger/f1-circuits, MIT License, (c) 2019-2025 Tomislav Bacinger.',
       '// Local metres (x east, y south). Point 0 = start/finish line, order = racing direction.',
       '', 'export const CIRCUIT_SHAPES: Record<string, [number, number][]> = {']
for gid, did in IDS.items():
    c = feats[did]['geometry']['coordinates']
    if math.hypot(c[0][0] - c[-1][0], c[0][1] - c[-1][1]) < 1e-7:
        c = c[:-1]
    lat0 = sum(p[1] for p in c) / len(c)
    lon0 = sum(p[0] for p in c) / len(c)
    kx = math.cos(math.radians(lat0)) * 111320
    pts = [(round((p[0] - lon0) * kx), round(-(p[1] - lat0) * 110540)) for p in c]
    out.append(f"  {gid}: [{', '.join(f'[{x}, {y}]' for x, y in pts)}],")
out.append('};')
open('src/sim/circuitShapes.ts', 'w').write('\n'.join(out) + '\n')
print('wrote', len(IDS), 'circuits')
